### ISSUE TITLE
Question regarding framework

### ISSUE THREAD

**Issue by maxsudik** [naveenchr/SeleniumTDD#8]
Hi Naveen, I found your selenium project on GitHub and it looks so clean and nice. Could you suggest which tutorial did you use to create this framework? I would appreciate it if you could send me an email with some suggestions.
Thank you in advance,
Max
maxsudik@gmail.com

**Comment by naveenchr** [comment]
Hi Max,

Glad to know that you found the framework helpful. I have mostly referred to the below udemy training to get things started.
Rest I have added in from my experience. But the training would be a good place for you to start if you are new to automation.

You can also follow the below trainers to get the latest updates around test automation.

**Elearning:** https://www.udemy.com/course/selenium-real-time-examplesinterview-questions

**Trainers:** 
https://www.linkedin.com/in/rahul-shetty-trainer/
https://www.linkedin.com/in/naveenkhunteta/
https://www.linkedin.com/in/karthikkk/

Regards,
Naveen
